[package]
name = "pre-signup"
version = "0.1.0"
edition = "2021"

[dependencies]
aws_lambda_events = { workspace = true }
lambda_runtime = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }